### ISSUE TITLE
CHROME MOD

### ISSUE THREAD

**Issue by 0u44** [YUHev2BeMed/YUHev2BeMed#1]
HEY!!!!! i got the mod menu for you if you still want it...
[Mod Menu.txt](https://github.com/YUHev2BeMed/YUHev2BeMed/files/10727549/Mod.Menu.txt)
there you go :)

**Comment by mfg471** [comment]
THANK YOU SO MUCH!!!!!
:)
I think I can be able to access it with Mac...
the text
>I love your stuff 😄

**Comment by 0u44** [comment]
you should be able to... and your welcome

**Comment by IloveFoxes366** [comment]
:)
